src/components/Card/Card.tsx

link url
[[C_UIUX] Mac > Landing 좌우 간격이 상이함](https://bclabs.atlassian.net/browse/PLAYV-1183)
- grid -> flex로 교체하여 컨텐츠 넘침 방지
- 고정너비 -> col-span-3 로 교체

fix/PLAYV-1183 #comment PLAYV-1183 "카드 flex로 변경 및 col-span-3 추가"

---

src/components/Alert/Alert.tsx
src/components/TextInput/TextInput.tsx

link url
[[C_UIUX] Header > 마우스 호버 > 발생한 툴팁 문구 줄바꿈이 디자인과 상이함](https://bclabs.atlassian.net/browse/PLAYV-1217)
- 얼럿의 제목 텍스트를 왼쪽으로 정렬했습니다.
- textInput 의 버튼 타입을 button으로 수정했습니다.

Bugfix/playv 1217 얼럿 텍스트정렬 왼쪽으로 수정

---

src/components/Alert/Alert.tsx

z-index가 오버라이드 안 되는 문제가 있어서 다시 수정했습니다.
이미 선언된 z-10을 z-[10]으로 변경했습니다.

fix: Alert 스타일링 변경

---

src/components/Card/Card.tsx

link url
- Manual Strategies 페이지에서 사용되는 카드의 너비가 달라(기존: 343px , Manual Strategies page: 374px) className을 추가하여 너비를 수정하여 사용할 수 있도록 변경했습니다.

PLAYV-1316 #comment "카드에 optional className 프롭으로 추가"

---

src/components/Chip/Chip.tsx

link url
https://bclabs.atlassian.net/browse/PLAYV-1378
- buy 모달 작업을 위해 count가 없을 경우 텍스트만 있는 칩을 표시하도록 변경했습니다.
- 너비를 유연하게 사용하기 위해 className 을 optional prop으로 추가했습니다.

Fix/PLAYV-1378 텍스트만 있는 chip

---

src/components/Modal/Modal.tsx

[link](https://bclabs.atlassian.net/browse/PLAYV-1476?atlOrigin=eyJpIjoiYzI2NmJmNjhkMTI5NGVkZjkyOTI5MGZiZjg5MTk0Y2EiLCJwIjoiaiJ9)
- 모달 배경을 클릭했을 때 닫힘 여부를 정할 수 있는 플래그 추가
- onOutsideClick props이고 기본이 true이며 원하지 않을 경우 false를 넣으면 됩니다

PLAYV-1476 #comment fix: 모달 배경 클릭시 모달 닫힘 플래그 추가

---

src/components/Badge/BadgeLabel.tsx
src/components/Badge/index.ts

link url
[[FRONT-END] 공통-Badge 타입 추가](https://bclabs.atlassian.net/browse/PLAYV-1482)
- 대각 벳지 컴포넌트 생성했습니다.
- text 프롭으로 뱃지 안의 텍스트를 바꿀 수 있습니다.
- status 로 뱃지 색깔을 바꿀 수 있습니다.
- className 을 추가하여 뱃지 위치를 조절할 수 있습니다.

PLAYV-1482 #comment "meut - Badge_Label 컴포넌트 추가"

---

src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/index.ts
src/components/Tooltip/style.css
src/components/index.ts
src/stories/Tooltip.stories.tsx

link url https://bclabs.atlassian.net/browse/PLAYV-1700
- 퀀트 카드에서 쓰일 툴팁 미리 만듦
- 추후에 툴팁 풍선만 남기고 현재 임시로 들어가있는 내부 코드(퀀트 카드 툴팁내용)는 드러내서 리뉴얼에서 children으로 내려주도록 코드 수정필요 (최종적으로는 툴팁 풍선만 남아서 다른 툴팁으로도 재사용되도록)

PLAYV-1700 add: Tooltip

---

src/components/Button/Button.tsx
src/components/TextInput/TextInput.tsx

link url https://bclabs.atlassian.net/browse/CNVSTR-2012
- TextInput focus앞에 hover 삭제, placeholder font-medium 추가
- Button active 색상 수정
- 피그마 https://www.figma.com/file/mDHKwkELe0uoMbtTUYsOHU/%5B%EB%94%94%EC%9E%90%EC%9D%B8%5D-Investor-Web-Design-System-v.1.0.0?node-id=167%3A8077&t=whErUAmx5jIPxjOn-1

CNVSTR-2012 fix: TextInput focus앞에 hover 삭제, placeholder font-medium 추가

---

src/components/ProfilePhoto/ProfilePhoto.tsx
src/stories/ProfilePhoto.stories.tsx

link url
https://bclabs.atlassian.net/browse/CNVSTR-2044
- ProfileImage 에 rounded-[8px] 옵션을 추가했습니다.
- rounded 옵션이 들어간 스토리북 추가하였습니다.
- rounded를 추가하지 않았을 때 rounded-full / 추가하였을 때 rounded-[8px] 입니다.
- 사용예시
```jsx
<ProfilePhoto
size="medium"
imageFile={imageURL || '/images/Header/Avatar_Profile_Default.svg'}
rounded
/>
```
| rounded | rounded 없을 떄(기본) |
|---|---|
|![스크린샷 2023-04-06 오후 5 05 44](https://user-images.githubusercontent.com/114374519/230314405-241fae39-50d6-4aaa-be46-0747523e2f3c.png) | ![스크린샷 2023-04-06 오후 5 06 02](https://user-images.githubusercontent.com/114374519/230314449-e1f8a50d-2659-48e0-88b6-68ea88e7a3cc.png) |

CNVSTR-2044 #comment "ProfilePhoto에 rounded-[8px] 속성 추가"

---

package.json
src/components/Tooltip/Tooltip.tsx
src/components/TooltipWithSteps/TooltipWithSteps.tsx
src/components/TooltipWithSteps/index.ts
src/components/index.ts
src/stories/Tooltip.stories.tsx
src/stories/TooltipWithSteps.stories.tsx

link url
[FRONT-END] SDQ > Performance > Price 박스 텍스트 수정 및 툴팁 추가
https://bclabs.atlassian.net/browse/CNVSTR-2069
- 변경된 툴팁 디자인 적용했습니다.
- 텍스트만 들어간 툴팁과 Steps 가 들어간 툴팁을 분리하였습니다.
eg. 
질문: 지금 당장은 Steps(스크린샷의 숫자가 들어있는 동그라미: ([피그마링크](https://www.figma.com/file/mDHKwkELe0uoMbtTUYsOHU/%5B%EB%94%94%EC%9E%90%EC%9D%B8%5D-Investor-Web-Design-System-v.1.0.0?node-id=6516-59769&t=6DtajOOSdOi1Rurm-4)) 를 사용하지 않아서 기존에 있던 Steps를 분리했는데요, 
이전 코드와 같이
```jsx
<Tooltip>
{children}
</Tooltip>
```
툴팁 구조를 원래대로 children 에 Steps나 텍스트를 넘겨주고 Steps 가 들어갔을때 툴팁의 스타일 클래스를 변경해주는 코드를 추가하는게 더 나을까요?
| 변경 전 | 변경 후 |
|---|---|
| ![스크린샷 2023-04-21 오후 6 08 33](https://user-images.githubusercontent.com/114374519/233596048-9b33b61e-fbb3-457e-905b-98648d59dae8.png) |  ![스크린샷 2023-04-21 오후 6 03 …

Cnvstr 2069 툴팁 디자인 변경 및 스텝 과 분리

---

package.json
src/components/Tooltip/Tooltip.tsx

link url
https://bclabs.atlassian.net/browse/CNVSTR-2147
[Quant] Safari > Price 툴팁 아이콘 마우스 호버 > 이외의 영역으로 마우스 이동 시 툴팁 자국이 남음
- safari에서 전략 상세 퍼포먼스 영역 툴팁의 drop-shadow 필터 자국이 남지않도록 수정했습니다.
로컬테스트 완료했습니다

Cnvstr 2147 [Quant] Safari > Price 툴팁 아이콘 마우스 호버 > 이외의 영역으로 마우스 이동 시 툴팁 자국이 남음

---

meut-preset.cjs
package.json

link url
[[FRONT-END] 공통 > Typography텍스트 Line-height 기존 세팅으로 원상 복귀](https://bclabs.atlassian.net/browse/CNVSTR-2024)
- 글로벌 세팅에서 text-xs 일때 line-height 20px 을 삭제했습니다.

Cnvstr 2024 [FRONT-END] 공통 > Typography텍스트 Line-height 기존 세팅으로 원상 복귀

---

package.json

없음
빌드스크립트 문제로 배포가 잘못되고 있었습니다. 
관련 PR: https://github.com/bclabs-org/meut-ui-react/pull/193
해당 부분 수정하고 버전 원복했습니다.

chore: 배포때문에 올린 버전 원복

---

package.json
src/components/Tooltip/Tooltip.tsx

link url
https://bclabs.atlassian.net/browse/CNVSTR-2300
- 툴팁 말풍선 화살표 부분을 가상요소로 변경하여 툴팁 영역이 아닌 부분도 툴팁 영역으로 인식되던 문제를 수정했습니다.
- position 과 left, bottom 클래스를 제거하여 라이브러리를 사용하는 쪽에서 툴팁위치를 변경 할 수 있도록 수정했습니다.

[개발][Quant] Algo strategies 탭 리뉴얼 사전 작업 - 툴팁 스타일링 변경

---

package.json

빌드 에러 픽스입니다.
빌드 완료 이후 publish 단계에서 1.3.2 버전이 이미 존재한다고 하여 버전 명시를 변경하여 다시 pr 올렸습니다.

fix: build error fix 1.3.2 -> 1.3.3

---

package.json
src/components/Dropdown/Dropdown.tsx

link url
- 티켓이 없는 일감입니다.
- label이 없어도 label이 렌더링 되어 마진이 생기는 문제
- Dropdown 컴포넌트 label이 있을 때만 label 렌더링하여 마진 생기지 않도록 변경
- 변경 전
- 변경 후

Bugfix/Dropdown 컴포넌트 label이 있을 때만 label 렌더링하여 마진 생기지 않도록 변경

---

package.json
src/components/Modal/Modal.tsx

link url
- https://bclabs.atlassian.net/browse/CNVSTR-1946
- 모달 열린 상태에서 마우스 클릭한 상태로 모달 영역 바깥으로 마우스가 나갈 시 모달이 닫히는 현상 수정했습니다.

Bugfix/CNVSTR-1946/모달 열린 상태에 마우스 드래그 시, 모달 바깥으로 커서가 나가면 모달 닫히는 문제 수정

---

package.json
src/components/Dropdown/Dropdown.tsx

link url
[Wallet] Convert > To 영역의 ticker 드롭다운 메뉴 버튼 미노출
https://bclabs.atlassian.net/browse/CNVSTR-2759
(해당 버그 수정 중 발견한 이슈입니다)
- 드롭다운 메뉴의 z-index가 클릭시 나타나는 옵션메뉴에 적용이 안되어 메뉴가 오픈되면 다른 요소뒤에 위치하는 문제 수정하였습니다.
수정 후

Bugfix/cnvstr 2759 드롭다운 메뉴 z-index 클릭시 나오는 메뉴에 적용

---

package.json
src/components/ButtonsGroup/ButtonsGroup.tsx
src/components/ButtonsGroup/buttonsGroup.css
src/components/ButtonsGroup/index.ts
src/components/index.ts
src/stories/ButtonsGroup.stories.tsx

link url
- [BM-302/[Wallet] Transaction history 페이지 > Type에 Convert 항목 추가 요청](https://bclabs.atlassian.net/browse/BM-302)
- Convert 탭 표시에 필요한 버튼 탭 컴포넌트 뮤트라이브러리로 공용화하였습니다.
- 피그마링크: https://www.figma.com/file/mDHKwkELe0uoMbtTUYsOHU/%5BCoinvestor%5D-Design-System-Web-v.1.2?type=design&node-id=2498-35447&mode=design&t=kQGIDkejIXEbdGZG-4
eg. 후속으로 병합해야하는 PR
- https://github.com/bclabs-org/coinvestor_investor-frontend/pull/1775

Feat/BM-302/Convert 탭 관련 ButtonsGroup 컴포넌트 공용화

---

package.json
src/components/Checkbox/Checkbox.tsx
src/stories/Checkbox.stories.tsx

link url
- https://bclabs.atlassian.net/browse/CNVSTR-2785
- https://www.figma.com/file/mDHKwkELe0uoMbtTUYsOHU/%5BCoinvestor%5D-Design-System-Web-v.1.2?type=design&node-id=171-17745&mode=design&t=WIk9BjI1TyamOOo4-4
- hover/focus/disabled 시 색상 추가, indeterminate ('-') 옵션 추가

Feat/CNVSTR-2785/hover/focus/disabled 시 색상 추가, indeterminate 옵션 추가

---

package.json
src/components/RadioButton/RadioButton.tsx
src/components/RadioButton/index.ts
src/components/RadioButtonGroup/RadioButtonGroup.tsx
src/components/RadioButtonGroup/RadioButtonGroupContext.ts
src/components/RadioButtonGroup/index.ts
src/components/index.ts
src/stories/RadioButtonGroup.stories.tsx

link url
- https://bclabs.atlassian.net/browse/CNVSTR-2786
- Radio Button 추가했습니다.
사용예시)
```tsx
const [selected, setSelected] = React.useState('1');
const handleChange = (value: string): void => {
setSelected(value);
};
return (
<>
<p className="font-medium text-gray-500">Current Select Id: {selected}</p>
<RadioButtonGroup
onChange={handleChange}
defaultCheckedId={selected}
legend="numbers"
className="mt-4"
>
<RadioButton id={'1'} label={'one'} />
<RadioButton id={'2'} label={'two'} />
<RadioButton id={'3'} label={'three'} />
</RadioButtonGroup>
</>
);
```

Feat/CNVSTR-2786/Radio Button Group 추가

---

package.json
src/components/RadioButton/RadioButton.tsx
src/components/RadioButtonGroup/RadioButtonGroup.tsx

link url
- 빌드에러 수정: column -> col 로 오타수정했습니다.
- UI 수정: groupDirection:col, labelDirection:col 일 때 아이템이 화면 왼쪽에 위치하도록 수정했습니다.
수정 전
수정 후

Fix/CNVSTR-2786 radio button group 빌드에러 픽스, 전시 형태 픽스

---

package.json
src/components/RadioButton/RadioButton.tsx
src/components/RadioButtonGroup/RadioButtonGroup.tsx
src/components/RadioButtonGroup/RadioButtonGroupContext.ts
src/stories/RadioButtonGroup.stories.tsx

link url
- https://bclabs.atlassian.net/browse/CNVSTR-2786
- 두 개 이상의 RadioButtonGroup 을 사용했을 때, 다른 그룹의 라디오 버튼과 같은 그룹으로 취급되는 현상 수정했습니다.
- 동일한 그룹안의 라디오버튼은 같은 name을 가질 수 있도록 Input.name attribute에 legend 값을 넣어주었습니다. 
수정 전
<video src="https://github.com/bclabs-org/meut-ui-react/assets/114374519/b67f3fd3-d704-4e24-a6ba-c09570ecc740"></video>
수정 후
<video src="https://github.com/bclabs-org/meut-ui-react/assets/114374519/d5cce822-c9dd-443a-b508-dd394d04498b"></video>

Bugfix/CNVSTR-2786/두개 이상의 RadioButtonGroup 컴포넌트를 동시에 사용했을 때 발생하는 문제 수정

---

package.json
src/components/TextInput/TextInput.tsx

link url
- input type이 number 일 때, 스크롤 이벤트가 발생시 요소 blur 처리하도록 수정했습니다. 

Bugfix/TextInput type="number" 일 때 스크롤 방지 

---

package.json
src/components/Modal/ErrorModal.tsx
src/stories/ErrorModal.stories.tsx

[CNVSTR-2806](https://bclabs.atlassian.net/browse/CNVSTR-2806)
코인베스터 공용 에러바운더리 적용을 위해 필요한 작업입니다.
현재 에러 모달 오른쪽 버튼에 모달 닫기 함수만 적용되어 있어 이를 수정하는 작업입니다.
[CNVSTR-2806]: https://bclabs.atlassian.net/browse/CNVSTR-2806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor/CNVSTR-2806/에러모달 오른쪽 버튼 핸들러 추가

---

src/components/Modal/Modal.tsx

[CNVSTR-2832](https://bclabs.atlassian.net/browse/CNVSTR-2832)
[모달 디자인](https://www.figma.com/file/TV5T2nwzkQPVRxnrj742nq/%5BCoinvestor%5D-Prototype-Web-v.1.4?type=design&node-id=186-2792&mode=dev)
Earn 페이지에 추가된 모달의 width 사이즈가 추가되어 디자인 라이브러리 모달에 option으로 추가하는 작업입니다.
large = 936px 옵션 추가했습니다.
[CNVSTR-2832]: https://bclabs.atlassian.net/browse/CNVSTR-2832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNVSTR-2832 #comment 모달 사이즈 large (936px) 추가

---

package.json
src/components/Modal/Modal.tsx

link url
- https://bclabs.atlassian.net/browse/CNVSTR-2868
-  https://bclabs.atlassian.net/browse/CNVSTR-2867 ← 해당 일감에서 모달 외 영역 클릭 시 리다이렉트 동작 구현을 위해 <Modal/> 컴포넌트에 모달이 닫힐 때 이벤트를 제어할 수 있도록 onClose 프롭 추가했습니다.

Feat / CNVSTR-2868 / Modal 컴포넌트에 onClose 프롭 추가

---

package.json
src/components/Modal/ErrorModal.tsx

[CNVSTR-2870](https://bclabs.atlassian.net/browse/CNVSTR-2870)
- Error Modal에 children, 닫기 버튼 props 옵션 추가
[CNVSTR-2870]: https://bclabs.atlassian.net/browse/CNVSTR-2870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor/cnvstr 2870/error modal props 수정

---

package.json
src/components/Alert/Alert.tsx
src/components/Toast/Toast.tsx
src/components/Toast/ToastStore.ts
src/components/Toast/types.ts
src/stories/Toast.stories.tsx

[CICK-18](https://bclabs.atlassian.net/browse/CICK-18)
- alert attention 색상이 yellow -> amber로 변경되어 반영했습니다.
- 해당 alert에 close button이 없어 toast()의 마지막 매개변수로 추가했습니다. default true로 주어서 기존 alert에는 영향 없앴습니다.
- ToastStore, Toast, Alert 수정했습니다.
| closeBtn 디폴트 |
|-----|
| ![스크린샷 2024-03-26 16 16 43](https://github.com/bclabs-org/meut-ui-react/assets/117155299/77edbf67-0c7d-4ad7-8098-b4ac47722a1d) |
| closeBtn = false |
|-----|
| ![스크린샷 2024-03-26 16 12 19](https://github.com/bclabs-org/meut-ui-react/assets/117155299/e7f270d2-92d2-443a-b666-4e1fe61278a0) |
[CICK-18]: https://bclabs.atlassian.net/browse/CICK-18?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor/toast 컬러 변경 및 closeBtn 옵션 추가
