- src/components/Button/Button.tsx
- Button size별 fontSize, fontWeight, padding 추가
> fix: Button 수정

- .github/workflows/config.yml
link url
자동번들, 자동 배포를 위한 작업 진행했습니다
https://github.com/bclabs-org/meut-ui-react/pull/50 먼저 리뷰해야 됩니다
> GitHub workflows build and deploy

- src/stories/Button.stories.tsx
link url
테스트겸 삭제된 medium 사이즈 스토리에서도 삭제했습니다 
> feat: medium 삭제됨. 스토리북에 반영

- .github/workflows/config.yml
> fix: 토큰명 변경함

- src/stories/ProfilePhoto.stories.tsx
> Test profile

- .github/workflows/config.yml
- src/stories/TextInput.stories.tsx
link url
배포시 발생하는 에러 픽스하고 workflow 단계 세분화 했습니다
> Who you are

- .github/workflows/config.yml
> fix: run key 빠져서 발생한 버그 픽스

- src/stories/TextInput.stories.tsx
> feat: 테스트를 위한 추가

- .github/workflows/config.yml
- src/stories/Button.stories.tsx
> Who you are test

- .github/workflows/config.yml
> fix: user name 변경

- src/stories/Button.stories.tsx
> feat: 테스트용 버튼 템플릿 추가

- .github/workflows/config.yml
- src/stories/Button.stories.tsx
> Deploy storybook test

- src/stories/TextInput.stories.tsx
> 테스트를 위한 커밋

- .github/workflows/config.yml
- src/stories/TextInput.stories.tsx
> Storybook test

- .github/workflows/config.yml
- src/stories/TextInput.stories.tsx
> test: key 변경

- .github/workflows/config.yml
> feat: 테스트를 위한 코드

- .github/workflows/config.yml
> fix:fix wrong code bug

- .github/workflows/config.yml
> fix:fix wrong code bug2

- .github/workflows/config.yml
> fix: 토큰 변경

- .github/workflows/config.yml
> fix: deploy test

- .github/workflows/config.yml
> fix: user name, user email 수정

- src/stories/Button.stories.tsx
link url
github actions 테스트 할 겸 버튼 스토리 하나 추가했습니다
> feat: 버튼 disaled 스토리 추가

- .github/workflows/deploy.yml
- .github/workflows/rollup-build.yml
link url
브랜치 디벨롭 -> 마스터로 변경했습니다
스토리북 배포와 빌드 푸시 플로우 분리했습니다
> feat: github actions workflow 분리

- src/components/Button/Button.tsx
- src/stories/Tabs.stories.tsx
> 테스트 코드, 원복할 예정

- .github/workflows/deploy.yml
- .github/workflows/rollup-build.yml
> fix: fix wrong paths

- src/components/Button/Button.tsx
- src/stories/Tabs.stories.tsx
> 테스트 코드 원복함

- src/components/Alert/Alert.tsx
- src/stories/Alert.stories.tsx
- src/stories/Checkbox.stories.tsx
link url https://bclabs.atlassian.net/browse/PLAYV-1141
- Alert Completion 추가
> PLAYV-1141 #comment add: Alert Completion

- src/components/Checkbox/Checkbox.tsx
> fix: checkbox

- src/components/Alert/Alert.tsx
link url
github actions 테스트를 위해 components 폴더 하위 코드 정리했습니다.
> style: 코드정리(테스트를 위해)

- src/components/TextInput/TextInput.tsx
link url
- extra message에 underline추가함
> add: underline

- src/components/Dropdown/Dropdown.tsx
- src/components/Tabs/Tabs.tsx
- src/components/TextInput/TextInput.tsx
link url https://bclabs.atlassian.net/browse/PLAYV-1271
- TextInput, Dropdown placeholder text 색상 수정
- Dropdown items z-index 추가
> fix: TextInput, Dropdown

- src/components/index.ts
> fix: 누락된 코드 추가. chip export

- src/components/TextareaInput/TextareaInput.tsx
- src/components/TextareaInput/index.ts
- src/components/index.ts
- src/stories/TextareaInput.stories.tsx
link url
[[FRONT-END] Text area Input 등록](https://bclabs.atlassian.net/browse/PLAYV-1186)
- textareaInput 컴포넌트를 생성했습니다.
- 스토리북 업데이트 했습니다.
> Playv 1186 text area input 등록

- src/components/TextInput/TextInput.tsx
> fix: extra

- src/components/Chip/Chip.tsx
[link url](https://bclabs.atlassian.net/browse/PLAYV-1223) 추가작업
클릭이벤트 추가 했습니다
> feat: props 추가, click event 구현

- src/components/Card/Card.tsx
- src/stories/Card.stories.tsx
- tailwind.config.cjs
[link url](https://bclabs.atlassian.net/browse/PLAYV-1088)
gradient 색상 추가했고 카드 테마 색상 추가했습니다.
> feat: gradient 색상 두가지 추가, card 테마 색상 추가

- src/components/Card/Card.tsx
- src/stories/Card.stories.tsx
> fix: color 옵셔널로 변경(빌드에러 픽스), 스토리 수정

- src/components/Alert/Alert.tsx
[link](https://bclabs.atlassian.net/browse/PLAYV-1305?atlOrigin=eyJpIjoiN2Y1OWM5ODY3MDM0NGE3YWFiOGVjNmViYjcyMmM3M2EiLCJwIjoiaiJ9)
- 사용자가 추가한 className이 반영될 수 있게 ${classNam} 위치 변경
> Feature/playv 1305 dev frontend alert 스타일링 개선

- src/components/Tabs/Tabs.tsx
> fix: className props 추가

- src/components/TextInput/TextInput.tsx
> fix: onChange 함수에 이벤트 파라미터 추가

- src/components/Alert/Alert.tsx
link url https://bclabs.atlassian.net/browse/PLAYV-1478
- background show 여부 추가
> PLAYV-1478 add: isBackgroundShow

- src/components/Alert/Alert.tsx
link url https://bclabs.atlassian.net/browse/PLAYV-1478
- fixed, z-index 삭제
> fix: Alert

- src/components/Dropdown/Dropdown.tsx
- Dropdown handleChange props 추가
> add: handleChange

- src/components/index.ts
link url
https://bclabs.atlassian.net/browse/PLAYV-1482
- BadgeLabel 컴포넌트를 component/index 에서 누락하여 추가하였습니다.
> PLAYV-1482 #comment "fix/component/index.ts 에 BadgeLabel 추가"

- src/components/TextInput/TextInput.tsx
- src/stories/TextareaInput.stories.tsx
link url https://bclabs.atlassian.net/browse/PLAYV-1361
- 우측에 currency 부분을 위해 props 추가함
> PLAYV-1361 add: currency

- src/components/Tabs/Tabs.tsx
> fix: 잘못된 코드 수정

- src/components/Tabs/Tabs.tsx
- 탭이 기존에는 2, 3개밖에 넣을 수 없어 1 ~ 8개까지 받을 수 있도록 수정했습니다
> fix: Tabs 기능 추가

- src/components/Modal/Modal.tsx
link url https://bclabs.atlassian.net/browse/PLAYV-1678
- Modal padding top, bottom 추가
> PLAYV-1678 fix: Modal padding

- src/components/TextareaInput/TextareaInput.tsx
link url https://bclabs.atlassian.net/browse/PLAYV-1736
- TextareaInput css 수정
> PLAYV-1736 fix: TextareaInput css

- src/components/Card/Card.tsx
link url https://bclabs.atlassian.net/browse/PLAYV-1634
- border -> ring으로 바꿈
> PLAYV-1634 fix: Card border->ring

- src/components/Card/Card.tsx
Reverts bclabs-org/meut-ui-react#140
> Revert "PLAYV-1634 fix: Card border->ring"

- .github/workflows/rollup-build.yml
- package.json
https://bclabs.atlassian.net/browse/CNVSTR-1851
github packages로 배포를 위한 세팅, github actions로 packages 배포 자동화 하는 작업 했습니다
테스트를 위해 우선 머지합니다.
> Deploy GitHub packages

- .github/workflows/rollup-build.yml
- src/components/Card/Card.tsx
> fix: 테스트를 위한 코드 원복, github actions 빌드에러 픽스

- src/components/Card/Card.tsx
> fix:test를 위한 코드 추가

- .github/workflows/rollup-build.yml
> fix: fix wrong code bug

- src/components/Modal/Modal.tsx
[link](https://bclabs.atlassian.net/browse/CNVSTR-1868?atlOrigin=eyJpIjoiMmZkNjU3NDMzN2E0NDY3YmE2N2VhNTI3MDhmZGU3MzciLCJwIjoiaiJ9)
- Modal에 widthSize는 optional prop을 추가해서 large를 넣으면 width가 718px이 될 수 있도록 변경
- 이 변경사항은 SDQ 구독 모달에 적용
> CNVSTR-1868 #comment width:718px인 사이즈 추가를 위해 widthSize props 추가

- .github/workflows/rollup-build.yml
- src/components/Alert/Alert.tsx
> fix: 불필요한 코드 삭제

- src/components/Alert/Alert.tsx
> test code 3

- .github/workflows/alpha-publish.yml
- .github/workflows/beta-publish.yml
- .github/workflows/release-publish.yml
- package.json
none
github packages 자동배포 구현 했습니다.
> feat: github packages 자동배포 구현

- package.json
- src/components/Toggle/Toggle.tsx
- src/components/Toggle/index.ts
- src/stories/Toggle.stories.tsx
- yarn.lock
link url https://bclabs.atlassian.net/browse/CNVSTR-904
- Toggle 컴포넌트 추가
> CNVSTR-904 add: Toggle

- src/components/Chip/Chip.tsx
- src/stories/Chip.stories.tsx
link url https://bclabs.atlassian.net/browse/CNVSTR-902
- Chip size, disabled 속성 추가
> CNVSTR-902 add: Chip size 추가

- src/components/Button/Button.tsx
link url https://bclabs.atlassian.net/browse/CNVSTR-1853
- button isProcessing props 추가
> CNVSTR-1853 add: processing

- src/components/Card/Card.tsx
link url https://bclabs.atlassian.net/browse/CNVSTR-1634
- Card의 border를 ring으로 변경 (카드안의 내용들이 안흔들리도록)
> CNVSTR-1634 fix: Card border -> ring

- src/components/TextareaInput/TextareaInput.tsx
link url https://bclabs.atlassian.net/browse/CNVSTR-1284
- TextareaInput 아이콘 수정
> CNVSTR-1284 fix: icons

- src/components/Tabs/Tabs.tsx
link url https://bclabs.atlassian.net/browse/CNVSTR-2051
- SDQ 탭스에 있는 스타일을 만들기 위해 상단 경계선 여부와 배경색 클래스를 props로 전달할 수 있게 변경
> CNVSTR-2051 #comment fix: 배경색, 상단 경계선을 props로 추가할 수 있음

- .github/workflows/alpha-publish.yml
- package.json
> fix: 스크립트 정리

- .github/workflows/alpha-publish.yml
> fix: 덜지운 코드 삭제

- package.json
> fix: 버전 변경. actions를 위해서. 다시 올릴 예정

- package.json
- src/components/Alert/Alert.tsx
https://bclabs.atlassian.net/browse/CNVSTR-2211
접근성 개선을 위해 아이콘 버튼에 aria-label 추가했습니다.
> Alert button aria label

- package.json
- src/components/Alert/Alert.tsx
- src/components/Tooltip/Tooltip.tsx
link url
https://bclabs.atlassian.net/browse/CNVSTR-2089
- 해당 일감의 뮤트부분 수정PR입니다. 
- text-xs 사용하는 부분중에 line-height:20px 이 적용되어야 하는 부분 수정
- tooltip
- alert
- #188 먼저 병합되어야 합니다.
- 로컬테스트 완료
> Cnvstr 2089 text-xs leading-5 적용

- package.json
> chore: 버전 올림

- .github/workflows/release-publish.yml
> fix: fix wrong deploy script

- package.json
> chore: 배포를 위한 수정

- package.json
- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/index.ts
- src/components/TextInput/TextInput.tsx
- src/stories/Dropdown.stories.tsx
- src/stories/TextInput.stories.tsx
Reverts bclabs-org/meut-ui-react#197
> Revert "feat: dropdown 포함된 input 구현"

- package.json
- src/components/Dropdown/Dropdown.tsx
이슈는 없고 https://bclabs.atlassian.net/browse/CNVSTR-2314 작업하는데 드롭다운을 쓸 수가 없어서 리팩터링 했습니다.
이슈에 적은 내용과 동일
> refactor: setSelected 삭제, handleChange만 사용하도록 수정

- package.json
- src/components/Tooltip/Tooltip.tsx
- src/stories/TextInput.stories.tsx
link url
- master 에 바로 병합하여 dveleop 에 누락되었던 1.1.1 버전 툴팁 관련 변경내용을 1.1.4 버전으로 업데이트 하여 병합하는 PR입니다. 
> develop 에 누락된 1.1.1 버전 1.1.4 버전으로 병합

- package.json
- src/components/TextInput/TextInput.tsx
> feat: number type 인풋 스핀 버튼 표시 안하도록 수정

- package.json
- src/components/Tooltip/Tooltip.tsx
link url
- 툴팁 디자인 변경
- 1.1.5 -> 1.1.6 버전 업데이트
> Tooltip width change

- package.json
- src/components/TextInput/TextInput.tsx
- TextInput에 disabled가 mini button, dropdown에도 적용되도록 추가함
- 버전 업데이트
> Cnvstr 2350

- package.json
- src/components/Button/Button.tsx
link url https://bclabs.atlassian.net/browse/CNVSTR-2463
- button size 추가
- 버전 업데이트
> Cnvstr 2463

- package.json
- src/components/Button/Button.tsx
link url https://bclabs.atlassian.net/browse/CNVSTR-2666
- isProcessing === true 일 때 disabled 되도록 수정
- 버전 업데이트
> Cnvstr 2666

- tsconfig.json
Build error fix 입니다.
es5 -> ES2015
> fix: build error fix es5 -> es2015

- package.json
빌드 에러 픽스입니다.
버젼 1.3.2를 작성하지 않아 바로 이전 pr이 배포되지 않아 수정했습니다.
> fix: build error fix 2.3.1 -> 1.3.2

- package.json
- src/components/Modal/Modal.tsx
[link url](https://bclabs.atlassian.net/browse/CNVSTR-2742?atlOrigin=eyJpIjoiMzcxNmI3MjI5NWI1NDljN2FkOGY1ODEzMWYxZGNiYTIiLCJwIjoiaiJ9)
Modal 위치 조정
> fix modal position on mobile

- package.json
- src/components/Modal/Modal.tsx
티켓 없는 작업
Mac OS 전체화면 기준 모달 닫힐 때 애니메이션 어색한 부분 수정
> fix modal animation on modal close

- .github/workflows/alpha-publish.yml
link url
- 빌드시 lib 폴더 생성되는지 체크하는 스크립트 추가했습니다.
> Bugfix/빌드시 lib 폴터 체크하는 스크립트 추가

- .github/workflows/alpha-publish.yml
> fix: paths 임시제거

- package.json
> fix: files 배열에 lib 추가

- package.json
> fix: 1.3.9 -> 1.3.10 로 업데이트

- package.json
> Bugfix/ files 배열 삭제, npmignore 파일 생성

- .npmignore
- package.json
link url
- Build 시 lib 폴더 누락되는 문제 수정, 패키지 파일 및 폴더 간소화
> Bugfix/Build 시 lib 폴더 누락되는 문제 수정, 패키지 파일 및 폴더 간소화

- package.json
[CNVSTR-2832](https://bclabs.atlassian.net/browse/CNVSTR-2832)
[모달 디자인](https://www.figma.com/file/TV5T2nwzkQPVRxnrj742nq/%5BCoinvestor%5D-Prototype-Web-v.1.4?type=design&node-id=186-2792&mode=dev)
Earn 페이지에 추가된 모달의 width 사이즈가 추가되어 디자인 라이브러리 모달에 option으로 추가하는 작업입니다.
large = 936px 옵션 추가했습니다.
1.6.5로 버전 업데이트했습니다.
[CNVSTR-2832]: https://bclabs.atlassian.net/browse/CNVSTR-2832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNVSTR-2832 #comment

- package.json
link url
1.6.6 -> 1.6.7로 업데이트했습니다.
> fix: 1.6.6 -> 1.6.7

- package.json
- src/components/Button/Button.tsx
link url
- https://bclabs.atlassian.net/browse/CICK-34
- Button 컴포넌트에 className 프롭(클래스 덮어쓰기) 추가했습니다. 
> Feat / CICK-34 / Button 컴포넌트에 className 프롭(클래스 덮어쓰기) 추가

- package.json
- src/components/Modal/Modal.tsx
[CICK-56](https://bclabs.atlassian.net/browse/CICK-56)
CICK-56 작업의 선행입니다. 이 작업 머지되면 코인베스터로 PR 올리겠습니다.
[CICK-56]: https://bclabs.atlassian.net/browse/CICK-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Refactor/modal  props 및 모바일 대응 수정

- .github/workflows/storybook-deploy.yml
> Bugfix / 빌드에러수정 storybook node 버전 명시

- package.json
> fix: 버전 수정 (1.7.4 -> 1.7.5)

- package.json
Reverts bclabs-org/meut-ui-react#258
> Revert "fix: 버전 수정 (1.7.4 -> 1.7.5)"

- .github/workflows/storybook-deploy.yml
Reverts bclabs-org/meut-ui-react#257
> Revert "Bugfix / 빌드에러수정 storybook node 버전 명시"

- package.json
link url
Bugfix / legacy_storybook_build 스크립트 수정 / 버전 수정
> Bugfix / legacy_storybook_build 스크립트 수정 / 버전 수정

- package.json
> fix: storybook 재배포 1.7.5 -> 1.7.6

- src/stories/Toast.stories.tsx
> fix: storybook 재배포용 PR
